### ISSUE TITLE
Как задать value ?

### ISSUE THREAD

**Issue by lightsid** [MihailDev/yii2-ckeditor#16]
Здравствуйте! Подскажите пожалуйста, как задать значение value?
Нужно сделать редактирование новости, но вывести текст из базы в виджет, не получается.

**Comment by MihailDev** [comment]
покажите шаблон формы ( можно просто место где используется едитор)

**Comment by lightsid** [comment]
Проблему уже решил...
перед полем, явно указал значение для $model->text.
$model - объект формы,
text - поле input
