### ISSUE TITLE
iframe встраивается вместо контента

### ISSUE THREAD

**Issue by nihaha** [MihailDev/yii2-ckeditor#20]
Вывожу редактор через ActiveForm, в двух вьюхах выводится нормально, в третьей iframe с редактором встраивается вместо контента, т.е. ни полей формы, ни даже шаблона вьюхи нет. 
Везде вывожу его одинаково:
```
<?php
    echo $form->field($model, 'content')->widget(CKEditor::className(),[
        'editorOptions' => [
            'preset' => 'basic',
            'inline' => false,
        ],
    ]);
?>
```
Все js-скрипты подключаются на всех страницах одинаково, но на двух все ок, а на одной - беда.

**Comment by nihaha** [comment]
Путем экспериментов установил, что если поле в БД называется content, то редактор будет встраиваеться на место переменной $content лейаута. 
Проверьте по возможности.

**Comment by MihailDev** [comment]
скорее всего совпадают йдишники тэгов! проверь плизз!

**Comment by nihaha** [comment]
Блин, все же беда в чем-то другом. Проверил на другой модели и там было поле content в БД и все работало корректно. Наверное, проделки шаблона. К сожалению, ничего другого не ум  не приходит.
