### ISSUE TITLE
Не работает fuul версия

### ISSUE THREAD

**Issue by vov4ik08** [MihailDev/yii2-ckeditor#3]
Привет! По умолчанию подтягивает Standart ckeditor нет возможно включить full версию после обновления на ckeditor 4.4.0

**Comment by MihailDev** [comment]
да спасибо втечении суток исправлю

**Comment by MihailDev** [comment]
у ckeditor нет full стабильной версии!

**Comment by MihailDev** [comment]
извеняюсь за недобство! 
залил вручную версию 4.4.5_full как появится нормальная стабильная версия сразу поминяю!

проблема в названии версии (или в уровне стабильности)
"ckeditor/ckeditor": "dev-full/stable"
или
"ckeditor/ckeditor": "dev-full/4.4.x"
нужна

если установит
"ckeditor/ckeditor": "4.4.5" - это версия идёт как standart поэтому и не работает фулл версия
