### ISSUE TITLE
image upload not working 

### ISSUE THREAD

**Issue by engrashid** [MihailDev/yii2-ckeditor#4]
<?= $form->field($model, 'information')->widget(CKEditor::className(),[
     'editorOptions' => [
      'preset' => 'full', //разработанны стандартные настройки basic, standard, full данную возможность не обязательно использовать
      'inline' => false, //по умолчанию false,  
      'filebrowserUploadUrl'=>Yii::$app->getUrlManager()->createUrl('dashboard/test')
     ],
    ]);?>

with above code snippet i got bad request in ajax call.

**Comment by MihailDev** [comment]
I do not know how you make Ajax call
can you give me your controller, model and view files

**Comment by engrashid** [comment]
i am not making ajax call .when i click send to server button an ajax call triggered .
I tried to place my url in this call by supplying value to filebrowserUploadUrl property.
