### ISSUE TITLE
Image upload not working

### ISSUE THREAD

**Issue by MohammedAbir** [MihailDev/yii2-ckeditor#5]
I use this code 

<?= $form->field($model, 'information')->widget(CKEditor::className(),[
                    'editorOptions' => ElFinder::ckeditorOptions('elfinder',[
                        'preset' => 'full', 
                        'inline' => false, 
                        //'filebrowserUploadUrl'=>Yii::$app->getUrlManager()->createUrl('dashboard/test')
                    ]),

```
                /* [
                    'preset' => 'full', 
                    'inline' => false, 
                    //'filebrowserBrowseUrl'=>Yii::$app->getUrlManager()->createUrl('dashboard/test',['type'=>'Images']),
                    //'filebrowserUploadUrl'=>Yii::$app->getUrlManager()->createUrl('dashboard/test')
                ], */
            ]);?>
```

If fixed it please help

**Comment by MihailDev** [comment]
please show me your config file ( or only elfinder options)

**Comment by MohammedAbir** [comment]
this is my backend config file

<?php
$params = array_merge(
    require(**DIR** . '/../../common/config/params.php'),
    require(**DIR** . '/../../common/config/params-local.php'),
    require(**DIR** . '/params.php'),
    require(**DIR** . '/params-local.php')
);

return [
    'id' => 'app-backend',
    'basePath' => dirname(**DIR**),
    'controllerNamespace' => 'backend\controllers',
    'defaultRoute' => 'login',
    'bootstrap' => ['log'],
    'modules' => [],
    'components' => [
        'user' => [
            //'identityClass' => 'common\models\User',
            'identityClass' => 'backend\models\AdminUser',
            'enableAutoLogin' => true,
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
    ],
    'params' => $params,
];

**Comment by MohammedAbir** [comment]
this is my view file

use mihaildev\ckeditor\CKEditor;
use mihaildev\elfinder\ElFinder;

<?= $form->field($model, 'information')->widget(CKEditor::className(),[
                    'editorOptions' => ElFinder::ckeditorOptions('elfinder',[
                        'preset' => 'full', 
                        'inline' => false, 
                        'filebrowserUploadUrl'=>Yii::$app->getUrlManager()->createUrl('dashboard/test')
                    ]),

```
            ]);?>
```

**Comment by MihailDev** [comment]
now everything is working?
