### ISSUE TITLE
File upload not working

### ISSUE THREAD

**Issue by MohammedAbir** [MihailDev/yii2-ckeditor#6]
Bro display this error

missing file Unable to resolve the request "assets/ebddf4cc/js/i18n/elfinder.en.js". 

Unable to connect to backend.

Invalid Configuration – yii\base\InvalidConfigException

Unable to locate message source for category 'my'.

**Comment by MohammedAbir** [comment]
this is my config

<?php
$params = array_merge(
    require(**DIR** . '/../../common/config/params.php'),
    require(**DIR** . '/../../common/config/params-local.php'),
    require(**DIR** . '/params.php'),
    require(**DIR** . '/params-local.php')
);

return [
    'id' => 'app-backend',
    'basePath' => dirname(**DIR**),
    'controllerNamespace' => 'backend\controllers',
    'defaultRoute' => 'login',
    'bootstrap' => ['log'],
    'modules' => [],
    'components' => [
        'user' => [
            //'identityClass' => 'common\models\User',
            'identityClass' => 'backend\models\AdminUser',
            'enableAutoLogin' => true,
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
    ],
    'controllerMap' => [
        'elfinder' => [
            'class' => 'mihaildev\elfinder\Controller',
            'access' => ['@'], //глобальный доступ к фаил менеджеру @ - для авторизорованных , ? - для гостей , чтоб открыть всем ['@', '?']
            'disabledCommands' => ['netmount'], //отключение ненужных команд https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#commands
            'roots' => [
                [
                    'baseUrl'=>'@web',
                    'basePath'=>'@webroot',
                    'path' => 'files/global',
                    'name' => 'Global'
                ],
                [
                    'class' => 'mihaildev\elfinder\UserPath',
                    'path'  => 'files/user_{id}',
                    'name'  => 'My Documents'
                ],
                [
                    'path' => 'files/some',
                    'name' => ['category' => 'my','message' => 'Some Name'] //перевод Yii::t($category, $message)
                ],
                [
                    'path'   => 'files/some',
                    'name'   => ['category' => 'my','message' => 'Some Name'], // Yii::t($category, $message)
                    'access' => ['read' => '*', 'write' => 'UserFilesAccess'] // \* - для всех, иначе проверка доступа в даааном примере все могут видет а редактировать могут пользователи только с правами UserFilesAccess
                ]
            ]
        ]
    ],
    'params' => $params,
];

**Comment by MihailDev** [comment]
this option 'name' => ['category' => 'my','message' => 'Some Name'] trigger error

you must specify the category of translation

read article http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html#message-translation
