### ISSUE TITLE
i am using this widget, in windows OS its fine, linux error shown

### ISSUE THREAD

**Issue by sintret** [MihailDev/yii2-ckeditor#9]
exception 'yii\base\InvalidParamException' with message 'Invalid path alias: @mihaildev/ckeditor/editor' in /usr/share/nginx/www/urge/vendor/yiisoft/yii2/BaseYii.php:152 Stack trace: #0 /usr/share/nginx/www/urge/vendor/yiisoft/yii2/web/AssetBundle.php(128): yii\BaseYii::getAlias() #1 /usr/share/nginx/www/urge/vendor/yiisoft/yii2/base/Object.php(107): yii\web\AssetBundle->init() #2 (): yii\base\Object->__construct() #3 /usr/share/nginx/www/urge/vendor/yiisoft/yii2/di/Container.php(362): ReflectionClass->newInstanceArgs() #4 /usr/share/nginx/www/urge/vendor/yiisoft/yii2/di/Container.php(147): yii\di\Container->build() #5 /usr/share/nginx/www/urge/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container->get() #6 /usr/share/nginx/www/urge/vendor/yiisoft/yii2/web/AssetManager.php(219): yii\BaseYii::createObject() #7 /usr/share/nginx/www/urge/vendor/yiisoft/yii2/web/AssetManager.php(192): yii\web\AssetManager->loadBundle() #8 /usr/share/nginx/www/urge/vendor/yiisoft/yii2/web/View.php(284): yii\web\AssetManager->getBundle() #9 /usr/share/nginx/www/urge/vendor/yiisoft/yii2/web/AssetBundle.php(118): yii\web\View->registerAssetBundle() #10 /usr/share/nginx/www/urge/vendor/mihaildev/yii2-ckeditor/CKEditor.php(123): yii\web\AssetBundle::register() #11 /usr/share/nginx/www/urge/vendor/yiisoft/yii2/base/Widget.php(96): mihaildev\ckeditor\CKEditor->run() #12 /usr/share/nginx/www/urge/vendor/yiisoft/yii2/widgets/ActiveField.php(717): yii\base\Widget::widget() #13 /usr/share/nginx/www/urge/vendor/kartik-v/yii2-widget-activeform/ActiveField.php(522): yii\widgets\ActiveField->widget() #14 /usr/share/nginx/www/urge/backend/views/setting/_form.php(45): kartik\form\ActiveField->widget() #15 /usr/share/nginx/www/urge/vendor/yiisoft/yii2/base/View.php(325): include() #16 /usr/share/nginx/www/urge/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile() #17 /usr/share/nginx/www/urge/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile() #18 /usr/share/nginx/www/urge/backend/views/setting/update.php(21): yii\base\View->render() #19 /usr/share/nginx/www/urge/vendor/yiisoft/yii2/base/View.php(325): include() #20 /usr/share/nginx/www/urge/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile() #21 /usr/share/nginx/www/urge/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile() #22 /usr/share/nginx/www/urge/vendor/yiisoft/yii2/base/Controller.php(367): yii\base\View->render() #23 /usr/share/nginx/www/urge/backend/controllers/SettingController.php(125): yii\base\Controller->render() #24 (): backend\controllers\SettingController->actionUpdate() #25 /usr/share/nginx/www/urge/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array() #26 /usr/share/nginx/www/urge/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams() #27 /usr/share/nginx/www/urge/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction() #28 /usr/share/nginx/www/urge/vendor/yiisoft/yii2/web/Application.php(83): yii\base\Module->runAction() #29 /usr/share/nginx/www/urge/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest() #30 /usr/share/nginx/www/urge/backend/web/index.php(18): yii\base\Application->run() #31 {main}

**Comment by MihailDev** [comment]
Show your configuration file and web/index.php

**Comment by sintret** [comment]
oke its fixed now, miss configuration file

**Comment by tuannda** [comment]
I error smilar, @sintret: How to fix it?

**Comment by MihailDev** [comment]
Show your configuration file
and composer.json

**Comment by tuannda** [comment]
@MihailDev I change to @dev version and working fine. Thank you!

**Comment by Dreamer0x01** [comment]
Поймал такой же баг.
Решилось добавлением в файл .../config/main.php вот такого параметра:
`    'aliases'        => [
        '@mihaildev/ckeditor' => '@vendor/mihaildev/yii2-ckeditor',
    ],    
`
